### ISSUE TITLE
[BUG] Cellular demo doesn't build on windows

### ISSUE THREAD

**Issue by friesendrywall** [FreeRTOS/FreeRTOS#1098]
**Describe the bug**
Mqtt mutual auth demo with sara r4 doesn't build out of the box.

**Target**
Windows

**Host**
Windows 10

**To Reproduce**
Try to build demo on windows

**Expected behavior**
Build successfully

**Screenshots**
NA

**Additional context**
This doesn't build because the underlying FreeRTOS+TCP doesn't build, because glibconfig.h doesn't exists, and other issues.

**Comment by tony-josi-aws** [comment]
Hi @friesendrywall, thanks for taking time to report this issue. We will look into this and get back to you.

**Comment by friesendrywall** [comment]
The main build fails with this output - 

Build started...
1>------ Build started: Project: mqtt_mutual_auth_demo_with_sara_r4, Configuration: Debug Win32 ------
1>LINK : fatal error LNK1104: cannot open file 'D:\repos\full_freertos\FreeRTOS\FreeRTOS-Plus\VisualStudio_StaticProjects\FreeRTOS+TCP\build\FreeRTOS+TCP\Win32\Debug\FreeRTOS+TCP.lib'
1>Done building project "mqtt_mutual_auth_demo_with_sara_r4.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

I'm attaching the build results for FreeRTOS+TCP, which I tried to build to fix this error.
[FreeRTOS_TCP_log.txt](https://github.com/FreeRTOS/FreeRTOS/files/12882691/FreeRTOS_TCP_log.txt)

**Comment by chinglee-iot** [comment]
@friesendrywall 
Can you help to check your build configuration mentioned in the [page](https://learn.microsoft.com/en-us/visualstudio/ide/understanding-build-configurations?view=vs-2022)? If you are using `Debug_with_Libslirp`, please change it to `Debug` and re-build the project to feedback the result.

We observe the same log with `Debug_with_Libslirp` configuration and will look into it.

If you build the demo from `mqtt_mutual_auth_demo_with_sara_r4.sln`, the default configuration is `Debug`. The demo only uses `xLogToStdout`. You should be able to build this demo and run it without ethernet.

**Comment by friesendrywall** [comment]
See attached.
![Screenshot 2023-10-14 10 27 12](https://github.com/FreeRTOS/FreeRTOS/assets/5509710/3569d460-a024-4d07-9566-5ddc83173205)
![Screenshot 2023-10-14 10 28 48](https://github.com/FreeRTOS/FreeRTOS/assets/5509710/3361d7bc-eab1-4515-a9e2-ae7b1bf8cf64)

**Comment by chinglee-iot** [comment]
@friesendrywall 
Thank you for your information. I managed to reproduce the problem you mentioned with the following steps:
* Remove the FreeRTOS+TCP.lib in **FreeRTOS/FreeRTOS-Plus/VisualStudio_StaticProjects/FreeRTOS+TCP/build** folder. This is probably built result by other demo project.
* Use visual studio IDE instead of MSBuild.exe. MSBuild.exe can't reproduce this problem.

I create a PR #1101 to fix this issue. Please also give it a try.

Sorry for your time wasting on this problem and thank you for reporting this problem again. We will also consider to update the logging library to remove the dependency with FreeRTOS+TCP. With this feature, FreeRTOS+TCP is not required in cellular demo anymore.

**Comment by friesendrywall** [comment]
It looks like PR #1101 does fix this, thanks you.
