### ISSUE TITLE
[DOC] freertos.org directs to midway-auth.amazon.com

### ISSUE THREAD

**Issue by emilfihlman** [FreeRTOS/FreeRTOS#1256]
**Describe the issue**
freertos.org directs to some issue page

**Reference**
freertos.org

**Screenshot**
![Screenshot_20240823_220411_Chrome](https://github.com/user-attachments/assets/e79c9025-b64a-4004-9350-eaca90efedf6)

**Browser**
- Browser: Chrome Android
- Version: 127.0.6533.103

**Comment by xuelix** [comment]
Thanks for reporting the bug, we have recently updated the website. That might be a few links missed update.  If you can paste the exact link that leads to this, that'll be a great help to fix the issue.  Thanks

**Comment by emilfihlman** [comment]
> Thanks for reporting the bug, we have recently updated the website. That might be a few links missed update. If you can paste the exact link that leads to this, that'll be a great help to fix the issue. Thanks

It would be directly the link https://freertos.org and any link

**Comment by emilfihlman** [comment]
But it seems to work now

**Comment by AniruddhaKanhere** [comment]
Hello @emilfihlman,
Thank you for raising the bug report.

We were deploying some fixes to the website. The deployment failed though and caused the cloudfront distribution to be this was. We have since rolled it back. You should be able to access the website now.

Let me know if you want to keep this open or shall we close the ticket?

**Comment by aggarg** [comment]
As the redirection is working now, I am closing this ticket. Feel free to reopen if you need anything from us.
