### ISSUE TITLE
[BUG] xQueueSelectFromSet() does not return when xQueueOverwrite() is used and the queue is already full (queue size = 1)

### ISSUE THREAD

**Issue by jliu83** [FreeRTOS/FreeRTOS#1286]
**Describe the bug**
When using xQueueSelectFromSet() to wait on multiple queues, if one of the queues is of size 1 and used as a mailbox, when writing to this queue using xQueueOverwrite() when the queue already has an item, xQueueSelectFromSet() does not return to notify that a new item has been written. 

**Target**
- Development board: M5STICK-C
- Instruction Set Architecture: ESP32
- IDE and version: Arduino IDE 2.3.2
- Toolchain and version: not sure

**Host**
- Host OS: WIndows 11
- Version: n/a

**To Reproduce**
- Use project ... and configure with ...
- Run on ... and could observe ...

**Expected behavior**
xQueueSelectFromSet() should return with active queue if an overwrite event occurs on the queue, even if it was already full

**Screenshots**

**Additional context**
I am hoping the description is enough, I can provide repro code if needed, but it should be pretty straight forward to reproduce.

**Comment by rohitmadan07** [comment]
Hi @jliu83, The behaviour that you are observing is actually expected, you can check the comments [here](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/5f3bab1a3242640c6e031d9cfb1be756bd76fb3c/queue.c#L981). 

xQueueOverwrite internally calls xQueueSend with queue_OVERWRITE, and the number of items in the queue does not change. 
xQueueSelectFromSet returns the handle of the queue which contains the data and therefore, a call to xQueueReceive on the returned handle is guaranteed to succeed. For example usage of queue sets, you can checkout [this].(https://freertos.org/Documentation/02-Kernel/04-API-references/07-Queue-sets/01-xQueueCreateSet#:~:text=NULL%20is%20returned.-,Example%20usage%3A,-1). 

A typical application would look like:-

```
for( ;; )
{
    xActivatedMember = xQueueSelectFromSet( xQueueSet, portMAX_DELAY )

    /* We use a block time of 0 in xQueueReceive calls as they are guaranteed
     * to pass because xQueueSelectFromSet() would not have returned the handle
     * unless something was available. */
    if( xActivatedMember == xQueue1 )
    {
        xQueueReceive( xActivatedMember, &xReceivedFromQueue1, 0 );
        vProcessValueFromQueue1( xReceivedFromQueue1 );
    }
    else if( xActivatedMember == xQueue2 )
    {
        xQueueReceive( xActivatedMember, &xReceivedFromQueue2, 0 );
        vProcessValueFromQueue2( &xReceivedFromQueue2 );
    }
    .
    .
}
```
Now if there's a high priority task that does:-
1. xQueueSend -> will put handle of the queue in the xQueueSet
2. xQueueOverwrite -> if this also puts the same handle of the queue in xQueueSet.

When the application runs, xQueueReceive will succeed for the first one (xQueue1), but it will not succeed for the second one (xQueue2) because xQueueOverwrite would have caused the same handle to be added in the queue set again, although the number of items would not have changed after overwrite, breaking the xQueueSelectFromSet behaviour.

> empty the box first with xQueueReceive(), then xQueueOverwrite(). xQueueSelectFromSet() works correctly in this instance.

What you show in your workaround, is the recommended way. Let us know if you have further queries.
