### ISSUE TITLE
How to submit new port

### ISSUE THREAD

**Issue by cui632** [FreeRTOS/FreeRTOS#2]
Hi :

I 'd lke t submit a new platform porting to FREERTOS repo. but Got fail to commit. 
I tried to pull a new request, but there is no different branch to create. how to fix ?

Vincent

**Comment by RichardBarry** [comment]
I’m not completely sure how the repo is configured but others have submitted pull requests.  Did you use a process similar to that described here: https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/ ?

**Comment by cui632** [comment]
![image](https://user-images.githubusercontent.com/17327454/69401378-e718af00-0d2f-11ea-8a22-4ace35c8bf68.png)
Does it works ?

**Comment by xiaoxiacui** [comment]
I have recreated a new acoount to submit, it stil gets same result ...

**Comment by xiaoxiacui** [comment]
I know how to deal !  and have submit to a pull request successfully

**Comment by yuhui-zheng** [comment]
Hi, this repo is now kind of ready to accept PR. Though we are working on defining a generic process, we should be able to evaluate your PR and merge. 

ps: Your alias looks familiar and I think we sorted things out. :) I'm drafting a tutorial page for your port/demo, and shall get a review request in email shortly.

**Comment by xiaoxiacui** [comment]
Hi Yuhui:

 

Thank you for your efficient work. .

 

Please give me a notice kindly when my PR has been merged into mainstream and published out to download. 

 

The RISC-V platform shall be delay to port due to coronavirus outbreak.  I will notice you when we start at first time …

 

 

Best Regards,

Vincent Cui 

 

 

发件人: Yuhui.Zheng <notifications@github.com> 
发送时间: 2020年2月13日 9:49
收件人: FreeRTOS/FreeRTOS <FreeRTOS@noreply.github.com>
抄送: xiaoxiacui <xiaoxia_cui@c-sky.com>; Comment <comment@noreply.github.com>
主题: Re: [FreeRTOS/FreeRTOS] How to submit new port (#2)

 

Hi, this repo is now kind of ready to accept PR. Though we are working on defining a generic process, we should be able to evaluate your PR and merge.

ps: Your alias looks familiar and I think we sorted things out. :) I'm drafting a tutorial page for your port/demo, and shall get a review request in email shortly.
